### PR TITLE
Fixed Data Gap Bug

### PR DESCRIPTION
**Pull request by John-Ragland**
There are a bunch of tiny changes that I've made over the past week and a half that I haven't done a good job of tracking. Here are some of the main components:

- added a data_gap_mode feature
          this attribute of OOIHydrophoneData selects if the obspy merge function uses interpolation or numpy masked array

- fixed issue with starting in the middle of a gap
          for this problem, I just added one extra mseed file on the beginning and end of the st_all stream. Then saved the slicing and merging for after the program has looped through every data_url_list item. This does result in possibly downloading more mseed files then necessary which could slow down the program. A feature that could be added later is either a user input choice to decide to do this, or a check in software to see if the start_time or end_time are in a gap.

- fixed issue with a single mseed file being broken
          in the case of a broken mseed file, the program will print the broken file link. Nothing is added to st_all and the loop continues on as if nothing happens. When the streams are merged, the gap will either be interpolated or be masked

As far as the printing, I haven't been able to change much of that yet, and I think the functions still regurgitate alot of unhelpful information. I'm hoping to get to that soon, but I thought I could do it on a separate branch or even on main.

Since I changed a lot of small things, I would suggest testing out some of the code that you're running using this updated branch and see if we get any unexpected errors. 

Let me know what you think!

### CODE REVIEW

**Comment by John-Ragland** [comment]
Hey, have you gotten a chance to look into this branch?

**Comment by FelixSchwock** [comment]
Hey, sorry I haven't found the time to look into it and try out the new features. If you think that most of the bugs are eliminated by now, you can go ahead an merge it to the master branch. I'm currently not sure when I'll find the time to test the code.

**Comment by FelixSchwock** [comment]
I just took a look at the code in GitHub. You're adding an extra file at the beginning end end of each time period when requesting the data right? Will this always be done, or is this an optional feature? If a file is appended at the beginning and end would that mean that the amount of data that is requested is longer than specified?

**Comment by John-Ragland** [comment]
There was an error where if there was a data gap right at start time it would fail. To fix this I added 1 extra mseed file at the beginning and end of the stream. In line 276, any extra data would be cut out. I think the resulting output is the same either way, but it would increase the time slightly to pull data. I think it's a great idea make this optional. I can work on that soon.

**Comment by John-Ragland** [comment]
Currently, I'm working on a new get_acoustic_data_conc() function that (hopefully) will solve the blocked IP issue. It uses concurrent requests instead of parallel requests. And in my small amount of experimentation, it seems to work pretty fast.

I don't really know whole lot about concurrent requests though btw

**Comment by John-Ragland** [comment]
Okay, so now the append function is optional and the get_acoustic_data_conc is displayed in the demo.

I'm going to merge to master soon, unless you have any objections. There are still some bugs that I need to fix with the get_acoustic_data_conc function.

**Comment by FelixSchwock** [comment]
Looks good to me. You can merge the changes to the master whenever you're ready.

I don't really know anything about concurrent requests either. But if this makes the code work with the OOI server that would be awesome.

**Pull request merged**
